/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;
import java.awt.Image;
import java.awt.List;
import java.awt.Toolkit;
import java.io.File;
import java.math.RoundingMode;
import java.net.URI;
import java.net.URL;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.Locale;
import java.util.Random;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
/**
 *
 * @author Nghia
 */

/// nhung cho comment code duoc su dung de test khong xoa
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame 
     */
    int SIZE = 3;
    
    // luu cac trang thai da di qua
    ArrayList<model> saveState;
    
    // vi tri trang thai hien tai
    int curStatelocation = 0;
    
    public Frame() {
        initComponents();
        randomNumber();
        // khong hien len man hinh 
        runningTime.setVisible(false);
        totalSteps.setVisible(false);
    }
    
    // su dung de doi cho khi di chuyen
    int EmptyLocationChecker(JButton btn1 , JButton btn2){
         String BtnNumber = btn2.getText();
         if(BtnNumber.isEmpty()){
             btn2.setText(btn1.getText());
             btn1.setText("");
             return 1;
         }
         return 0;
    }
    
    // su dung de tinh so cap dao nguoc 
    // neu la chan thi co the giai duoc , le thi khong
    int countReversedPair(int[] a){
        int cnt = 0;
        for(int i=0;i<a.length-1;i++){
            for(int j=i+1;j<SIZE*SIZE;j++){
                if(a[i]!=0&&a[j]!=0&&a[i]>a[j]){
                    cnt++;
                }
            }
        }
        return cnt;
    }
    
    void randomNumber(){
        saveState = new ArrayList<>();
        jLabelTongSoDiChuyen.setText("0");
        curStatelocation = 0;
        int boardSize = SIZE;
        model puzzle = new model();
//        String [] num = {"1","2","3","4","5","6","","7","8"};
//        int [] arr = { 2 ,1, 3, 4 ,5, 6 ,8, 7 ,0 };
        int [] arr = new int[9];
        ArrayList<String> num = new ArrayList<>();

        for(int i=0;i<=8;i++){
            num.add(String.valueOf(i));
        }
        
        // neu vao truong hop khong giai duoc thi duyet lai
        while(true){
            Collections.shuffle(num);
            for(int i=0;i<SIZE*SIZE;i++){
                arr[i] = Integer.parseInt(num.get(i));
            }
            int checkSolve = countReversedPair(arr);
            if(checkSolve%2==0) break;
        }
        
        for(int i=0;i<SIZE*SIZE;i++){
            if(num.get(i).equals("0")){
                num.set(i, "");
            }
        }
        for(int i=0;i<SIZE;i++){
            for(int j=0;j<SIZE;j++){
                puzzle.board[i][j] = num.get(i*SIZE+j).equals("")?0:Integer.parseInt(num.get(i*SIZE+j));
            }
        }
        saveState.add(puzzle);
        btnBox1.setText(num.get(0));
        btnBox2.setText(num.get(1));
        btnBox3.setText(num.get(2));
        btnBox4.setText(num.get(3));
        btnBox5.setText(num.get(4));
        btnBox6.setText(num.get(5));
        btnBox7.setText(num.get(6));
        btnBox8.setText(num.get(7));
        btnBox9.setText(num.get(8));
        
        
//        jButtonPiece1.setText(num[0]);
//        jButtonPiece2.setText(num[1]);
//        jButtonPiece3.setText(num[2]);
//        jButtonPiece4.setText(num[3]);
//        jButtonPiece5.setText(num[4]);
//        jButtonPiece6.setText(num[5]);
//        jButtonPiece7.setText(num[6]);
//        jButtonPiece8.setText(num[7]);
//        jButtonPiece9.setText(num[8]);

    }    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTieuDe = new javax.swing.JPanel();
        jLabelTieuDe = new javax.swing.JLabel();
        jPanelKhungHinhAnh = new javax.swing.JPanel();
        btnBox3 = new javax.swing.JButton();
        btnBox1 = new javax.swing.JButton();
        btnBox2 = new javax.swing.JButton();
        btnBox8 = new javax.swing.JButton();
        btnBox7 = new javax.swing.JButton();
        btnBox9 = new javax.swing.JButton();
        btnBox4 = new javax.swing.JButton();
        btnBox5 = new javax.swing.JButton();
        btnBox6 = new javax.swing.JButton();
        labelSoBuocDiChuyen = new javax.swing.JLabel();
        jButtonDiLui = new javax.swing.JButton();
        jButtonDiToi = new javax.swing.JButton();
        jLabelTongSoDiChuyen = new javax.swing.JLabel();
        jButtonOut = new javax.swing.JButton();
        jButtonPlayAgain = new javax.swing.JButton();
        jButtonSolve = new javax.swing.JButton();
        runningTime = new javax.swing.JLabel();
        totalSteps = new javax.swing.JLabel();
        jPanelKhungHinhAnh1 = new javax.swing.JPanel();
        btnDich3 = new javax.swing.JButton();
        btnDich1 = new javax.swing.JButton();
        btnDich2 = new javax.swing.JButton();
        btnDich8 = new javax.swing.JButton();
        btnDich7 = new javax.swing.JButton();
        btnDich9 = new javax.swing.JButton();
        btnDich4 = new javax.swing.JButton();
        btnDich5 = new javax.swing.JButton();
        btnDich6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTieuDe.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTieuDe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 1, true));
        jPanelTieuDe.setForeground(new java.awt.Color(0, 51, 255));

        jLabelTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTieuDe.setText("                          Puzzle Game in Java");

        javax.swing.GroupLayout jPanelTieuDeLayout = new javax.swing.GroupLayout(jPanelTieuDe);
        jPanelTieuDe.setLayout(jPanelTieuDeLayout);
        jPanelTieuDeLayout.setHorizontalGroup(
            jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTieuDeLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabelTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(767, Short.MAX_VALUE))
        );
        jPanelTieuDeLayout.setVerticalGroup(
            jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1900, -1));

        jPanelKhungHinhAnh.setBackground(new java.awt.Color(255, 255, 255));
        jPanelKhungHinhAnh.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Trạng thái hiện tại"));
        jPanelKhungHinhAnh.setForeground(new java.awt.Color(0, 51, 255));

        btnBox3.setBackground(new java.awt.Color(255, 255, 204));
        btnBox3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnBox3.setText("3");
        btnBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBox3ActionPerformed(evt);
            }
        });

        btnBox1.setBackground(new java.awt.Color(255, 255, 204));
        btnBox1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnBox1.setText("1");
        btnBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBox1ActionPerformed(evt);
            }
        });

        btnBox2.setBackground(new java.awt.Color(255, 255, 204));
        btnBox2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnBox2.setText("2");
        btnBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBox2ActionPerformed(evt);
            }
        });

        btnBox8.setBackground(new java.awt.Color(255, 255, 204));
        btnBox8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnBox8.setText("7");
        btnBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBox8ActionPerformed(evt);
            }
        });

        btnBox7.setBackground(new java.awt.Color(255, 255, 204));
        btnBox7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnBox7.setText("8");
        btnBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBox7ActionPerformed(evt);
            }
        });

        btnBox9.setBackground(new java.awt.Color(255, 255, 204));
        btnBox9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBox9ActionPerformed(evt);
            }
        });

        btnBox4.setBackground(new java.awt.Color(255, 255, 204));
        btnBox4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnBox4.setText("4");
        btnBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBox4ActionPerformed(evt);
            }
        });

        btnBox5.setBackground(new java.awt.Color(255, 255, 204));
        btnBox5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnBox5.setText("5");
        btnBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBox5ActionPerformed(evt);
            }
        });

        btnBox6.setBackground(new java.awt.Color(255, 255, 204));
        btnBox6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnBox6.setText("6");
        btnBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBox6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelKhungHinhAnhLayout = new javax.swing.GroupLayout(jPanelKhungHinhAnh);
        jPanelKhungHinhAnh.setLayout(jPanelKhungHinhAnhLayout);
        jPanelKhungHinhAnhLayout.setHorizontalGroup(
            jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhungHinhAnhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKhungHinhAnhLayout.createSequentialGroup()
                        .addComponent(btnBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelKhungHinhAnhLayout.createSequentialGroup()
                        .addComponent(btnBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelKhungHinhAnhLayout.createSequentialGroup()
                        .addComponent(btnBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanelKhungHinhAnhLayout.setVerticalGroup(
            jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhungHinhAnhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelKhungHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 640, 660));

        labelSoBuocDiChuyen.setBackground(new java.awt.Color(255, 51, 51));
        labelSoBuocDiChuyen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelSoBuocDiChuyen.setForeground(new java.awt.Color(51, 51, 255));
        labelSoBuocDiChuyen.setText("Số bước di chuyển:");
        getContentPane().add(labelSoBuocDiChuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 830, 220, 70));

        jButtonDiLui.setBackground(new java.awt.Color(255, 204, 153));
        jButtonDiLui.setText("<<Đi lùi");
        jButtonDiLui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiLuiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDiLui, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 850, 130, 40));

        jButtonDiToi.setBackground(new java.awt.Color(255, 204, 153));
        jButtonDiToi.setText(" Đi tới>>");
        jButtonDiToi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiToiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDiToi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 850, 130, 40));

        jLabelTongSoDiChuyen.setBackground(new java.awt.Color(102, 51, 255));
        jLabelTongSoDiChuyen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTongSoDiChuyen.setForeground(new java.awt.Color(0, 51, 255));
        jLabelTongSoDiChuyen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTongSoDiChuyen.setText("0");
        jLabelTongSoDiChuyen.setToolTipText("");
        getContentPane().add(jLabelTongSoDiChuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 850, 100, -1));

        jButtonOut.setText("Out");
        getContentPane().add(jButtonOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 830, 130, 50));

        jButtonPlayAgain.setText("play again");
        jButtonPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayAgainActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 830, 130, 50));

        jButtonSolve.setText("Solve");
        jButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSolve, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 830, 120, 50));

        runningTime.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        runningTime.setText("Giải trong: ");
        getContentPane().add(runningTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 370, 40));

        totalSteps.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalSteps.setText("Số bước đi đến đích:");
        getContentPane().add(totalSteps, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 380, 40));

        jPanelKhungHinhAnh1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelKhungHinhAnh1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Trạng thái đích"));
        jPanelKhungHinhAnh1.setForeground(new java.awt.Color(0, 51, 255));

        btnDich3.setBackground(new java.awt.Color(204, 204, 255));
        btnDich3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDich3.setText("3");
        btnDich3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDich3ActionPerformed(evt);
            }
        });

        btnDich1.setBackground(new java.awt.Color(204, 204, 255));
        btnDich1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDich1.setText("1");
        btnDich1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDich1ActionPerformed(evt);
            }
        });

        btnDich2.setBackground(new java.awt.Color(204, 204, 255));
        btnDich2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDich2.setText("2");
        btnDich2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDich2ActionPerformed(evt);
            }
        });

        btnDich8.setBackground(new java.awt.Color(204, 204, 255));
        btnDich8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDich8.setText("8");
        btnDich8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDich8ActionPerformed(evt);
            }
        });

        btnDich7.setBackground(new java.awt.Color(204, 204, 255));
        btnDich7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDich7.setText("7");
        btnDich7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDich7ActionPerformed(evt);
            }
        });

        btnDich9.setBackground(new java.awt.Color(204, 204, 255));
        btnDich9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDich9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDich9ActionPerformed(evt);
            }
        });

        btnDich4.setBackground(new java.awt.Color(204, 204, 255));
        btnDich4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDich4.setText("4");
        btnDich4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDich4ActionPerformed(evt);
            }
        });

        btnDich5.setBackground(new java.awt.Color(204, 204, 255));
        btnDich5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDich5.setText("5");
        btnDich5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDich5ActionPerformed(evt);
            }
        });

        btnDich6.setBackground(new java.awt.Color(204, 204, 255));
        btnDich6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDich6.setText("6");
        btnDich6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDich6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelKhungHinhAnh1Layout = new javax.swing.GroupLayout(jPanelKhungHinhAnh1);
        jPanelKhungHinhAnh1.setLayout(jPanelKhungHinhAnh1Layout);
        jPanelKhungHinhAnh1Layout.setHorizontalGroup(
            jPanelKhungHinhAnh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhungHinhAnh1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKhungHinhAnh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKhungHinhAnh1Layout.createSequentialGroup()
                        .addComponent(btnDich1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDich2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDich3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelKhungHinhAnh1Layout.createSequentialGroup()
                        .addComponent(btnDich4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDich5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDich6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelKhungHinhAnh1Layout.createSequentialGroup()
                        .addComponent(btnDich7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDich8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDich9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanelKhungHinhAnh1Layout.setVerticalGroup(
            jPanelKhungHinhAnh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhungHinhAnh1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKhungHinhAnh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDich1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDich2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDich3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelKhungHinhAnh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDich4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDich5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDich6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelKhungHinhAnh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDich7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDich8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDich9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelKhungHinhAnh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 150, 640, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBox3ActionPerformed
        int check = 0 ;
        
        check+=EmptyLocationChecker(btnBox3, btnBox2);
        check+=EmptyLocationChecker(btnBox3, btnBox6);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = btnBox1.getText().equals("")?0:Integer.parseInt(btnBox1.getText());
            puzzle.board[0][1] = btnBox2.getText().equals("")?0:Integer.parseInt(btnBox2.getText());
            puzzle.board[0][2] = btnBox3.getText().equals("")?0:Integer.parseInt(btnBox3.getText());
            puzzle.board[1][0] = btnBox4.getText().equals("")?0:Integer.parseInt(btnBox4.getText());
            puzzle.board[1][1] = btnBox5.getText().equals("")?0:Integer.parseInt(btnBox5.getText());
            puzzle.board[1][2] = btnBox6.getText().equals("")?0:Integer.parseInt(btnBox6.getText());
            puzzle.board[2][0] = btnBox7.getText().equals("")?0:Integer.parseInt(btnBox7.getText());
            puzzle.board[2][1] = btnBox8.getText().equals("")?0:Integer.parseInt(btnBox8.getText());
            puzzle.board[2][2] = btnBox9.getText().equals("")?0:Integer.parseInt(btnBox9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_btnBox3ActionPerformed

    private void btnBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBox1ActionPerformed
        int check = 0;
        
        check+=EmptyLocationChecker(btnBox1, btnBox2);
        check+=EmptyLocationChecker(btnBox1, btnBox4);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = btnBox1.getText().equals("")?0:Integer.parseInt(btnBox1.getText());
            puzzle.board[0][1] = btnBox2.getText().equals("")?0:Integer.parseInt(btnBox2.getText());
            puzzle.board[0][2] = btnBox3.getText().equals("")?0:Integer.parseInt(btnBox3.getText());
            puzzle.board[1][0] = btnBox4.getText().equals("")?0:Integer.parseInt(btnBox4.getText());
            puzzle.board[1][1] = btnBox5.getText().equals("")?0:Integer.parseInt(btnBox5.getText());
            puzzle.board[1][2] = btnBox6.getText().equals("")?0:Integer.parseInt(btnBox6.getText());
            puzzle.board[2][0] = btnBox7.getText().equals("")?0:Integer.parseInt(btnBox7.getText());
            puzzle.board[2][1] = btnBox8.getText().equals("")?0:Integer.parseInt(btnBox8.getText());
            puzzle.board[2][2] = btnBox9.getText().equals("")?0:Integer.parseInt(btnBox9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_btnBox1ActionPerformed

    private void btnBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBox2ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        check+=EmptyLocationChecker(btnBox2, btnBox1);
        check+=EmptyLocationChecker(btnBox2, btnBox3);
        check+=EmptyLocationChecker(btnBox2, btnBox5);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = btnBox1.getText().equals("")?0:Integer.parseInt(btnBox1.getText());
            puzzle.board[0][1] = btnBox2.getText().equals("")?0:Integer.parseInt(btnBox2.getText());
            puzzle.board[0][2] = btnBox3.getText().equals("")?0:Integer.parseInt(btnBox3.getText());
            puzzle.board[1][0] = btnBox4.getText().equals("")?0:Integer.parseInt(btnBox4.getText());
            puzzle.board[1][1] = btnBox5.getText().equals("")?0:Integer.parseInt(btnBox5.getText());
            puzzle.board[1][2] = btnBox6.getText().equals("")?0:Integer.parseInt(btnBox6.getText());
            puzzle.board[2][0] = btnBox7.getText().equals("")?0:Integer.parseInt(btnBox7.getText());
            puzzle.board[2][1] = btnBox8.getText().equals("")?0:Integer.parseInt(btnBox8.getText());
            puzzle.board[2][2] = btnBox9.getText().equals("")?0:Integer.parseInt(btnBox9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_btnBox2ActionPerformed

    private void btnBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBox7ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        
        
        check+=EmptyLocationChecker(btnBox7, btnBox4);
        check+=EmptyLocationChecker(btnBox7, btnBox8);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = btnBox1.getText().equals("")?0:Integer.parseInt(btnBox1.getText());
            puzzle.board[0][1] = btnBox2.getText().equals("")?0:Integer.parseInt(btnBox2.getText());
            puzzle.board[0][2] = btnBox3.getText().equals("")?0:Integer.parseInt(btnBox3.getText());
            puzzle.board[1][0] = btnBox4.getText().equals("")?0:Integer.parseInt(btnBox4.getText());
            puzzle.board[1][1] = btnBox5.getText().equals("")?0:Integer.parseInt(btnBox5.getText());
            puzzle.board[1][2] = btnBox6.getText().equals("")?0:Integer.parseInt(btnBox6.getText());
            puzzle.board[2][0] = btnBox7.getText().equals("")?0:Integer.parseInt(btnBox7.getText());
            puzzle.board[2][1] = btnBox8.getText().equals("")?0:Integer.parseInt(btnBox8.getText());
            puzzle.board[2][2] = btnBox9.getText().equals("")?0:Integer.parseInt(btnBox9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_btnBox7ActionPerformed

    private void btnBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBox8ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        check+=EmptyLocationChecker(btnBox8, btnBox5);
        check+=EmptyLocationChecker(btnBox8, btnBox7);
        check+=EmptyLocationChecker(btnBox8, btnBox9);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = btnBox1.getText().equals("")?0:Integer.parseInt(btnBox1.getText());
            puzzle.board[0][1] = btnBox2.getText().equals("")?0:Integer.parseInt(btnBox2.getText());
            puzzle.board[0][2] = btnBox3.getText().equals("")?0:Integer.parseInt(btnBox3.getText());
            puzzle.board[1][0] = btnBox4.getText().equals("")?0:Integer.parseInt(btnBox4.getText());
            puzzle.board[1][1] = btnBox5.getText().equals("")?0:Integer.parseInt(btnBox5.getText());
            puzzle.board[1][2] = btnBox6.getText().equals("")?0:Integer.parseInt(btnBox6.getText());
            puzzle.board[2][0] = btnBox7.getText().equals("")?0:Integer.parseInt(btnBox7.getText());
            puzzle.board[2][1] = btnBox8.getText().equals("")?0:Integer.parseInt(btnBox8.getText());
            puzzle.board[2][2] = btnBox9.getText().equals("")?0:Integer.parseInt(btnBox9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_btnBox8ActionPerformed

    private void btnBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBox9ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        
        
        check+=EmptyLocationChecker(btnBox9, btnBox6);
        check+=EmptyLocationChecker(btnBox9, btnBox8);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = btnBox1.getText().equals("")?0:Integer.parseInt(btnBox1.getText());
            puzzle.board[0][1] = btnBox2.getText().equals("")?0:Integer.parseInt(btnBox2.getText());
            puzzle.board[0][2] = btnBox3.getText().equals("")?0:Integer.parseInt(btnBox3.getText());
            puzzle.board[1][0] = btnBox4.getText().equals("")?0:Integer.parseInt(btnBox4.getText());
            puzzle.board[1][1] = btnBox5.getText().equals("")?0:Integer.parseInt(btnBox5.getText());
            puzzle.board[1][2] = btnBox6.getText().equals("")?0:Integer.parseInt(btnBox6.getText());
            puzzle.board[2][0] = btnBox7.getText().equals("")?0:Integer.parseInt(btnBox7.getText());
            puzzle.board[2][1] = btnBox8.getText().equals("")?0:Integer.parseInt(btnBox8.getText());
            puzzle.board[2][2] = btnBox9.getText().equals("")?0:Integer.parseInt(btnBox9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_btnBox9ActionPerformed

    private void btnBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBox4ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        check+=EmptyLocationChecker(btnBox4, btnBox1);
        check+=EmptyLocationChecker(btnBox4, btnBox5);
        check+=EmptyLocationChecker(btnBox4, btnBox7);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = btnBox1.getText().equals("")?0:Integer.parseInt(btnBox1.getText());
            puzzle.board[0][1] = btnBox2.getText().equals("")?0:Integer.parseInt(btnBox2.getText());
            puzzle.board[0][2] = btnBox3.getText().equals("")?0:Integer.parseInt(btnBox3.getText());
            puzzle.board[1][0] = btnBox4.getText().equals("")?0:Integer.parseInt(btnBox4.getText());
            puzzle.board[1][1] = btnBox5.getText().equals("")?0:Integer.parseInt(btnBox5.getText());
            puzzle.board[1][2] = btnBox6.getText().equals("")?0:Integer.parseInt(btnBox6.getText());
            puzzle.board[2][0] = btnBox7.getText().equals("")?0:Integer.parseInt(btnBox7.getText());
            puzzle.board[2][1] = btnBox8.getText().equals("")?0:Integer.parseInt(btnBox8.getText());
            puzzle.board[2][2] = btnBox9.getText().equals("")?0:Integer.parseInt(btnBox9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_btnBox4ActionPerformed

    private void btnBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBox5ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        check+=EmptyLocationChecker(btnBox5, btnBox2);
        check+=EmptyLocationChecker(btnBox5, btnBox4);
        check+=EmptyLocationChecker(btnBox5, btnBox6);
        check+=EmptyLocationChecker(btnBox5, btnBox8);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = btnBox1.getText().equals("")?0:Integer.parseInt(btnBox1.getText());
            puzzle.board[0][1] = btnBox2.getText().equals("")?0:Integer.parseInt(btnBox2.getText());
            puzzle.board[0][2] = btnBox3.getText().equals("")?0:Integer.parseInt(btnBox3.getText());
            puzzle.board[1][0] = btnBox4.getText().equals("")?0:Integer.parseInt(btnBox4.getText());
            puzzle.board[1][1] = btnBox5.getText().equals("")?0:Integer.parseInt(btnBox5.getText());
            puzzle.board[1][2] = btnBox6.getText().equals("")?0:Integer.parseInt(btnBox6.getText());
            puzzle.board[2][0] = btnBox7.getText().equals("")?0:Integer.parseInt(btnBox7.getText());
            puzzle.board[2][1] = btnBox8.getText().equals("")?0:Integer.parseInt(btnBox8.getText());
            puzzle.board[2][2] = btnBox9.getText().equals("")?0:Integer.parseInt(btnBox9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_btnBox5ActionPerformed

    private void btnBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBox6ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        check+=EmptyLocationChecker(btnBox6, btnBox3);
        check+=EmptyLocationChecker(btnBox6, btnBox5);
        check+=EmptyLocationChecker(btnBox6, btnBox9);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = btnBox1.getText().equals("")?0:Integer.parseInt(btnBox1.getText());
            puzzle.board[0][1] = btnBox2.getText().equals("")?0:Integer.parseInt(btnBox2.getText());
            puzzle.board[0][2] = btnBox3.getText().equals("")?0:Integer.parseInt(btnBox3.getText());
            puzzle.board[1][0] = btnBox4.getText().equals("")?0:Integer.parseInt(btnBox4.getText());
            puzzle.board[1][1] = btnBox5.getText().equals("")?0:Integer.parseInt(btnBox5.getText());
            puzzle.board[1][2] = btnBox6.getText().equals("")?0:Integer.parseInt(btnBox6.getText());
            puzzle.board[2][0] = btnBox7.getText().equals("")?0:Integer.parseInt(btnBox7.getText());
            puzzle.board[2][1] = btnBox8.getText().equals("")?0:Integer.parseInt(btnBox8.getText());
            puzzle.board[2][2] = btnBox9.getText().equals("")?0:Integer.parseInt(btnBox9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
        
    }//GEN-LAST:event_btnBox6ActionPerformed

    private void jButtonDiLuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiLuiActionPerformed
        // TODO add your handling code here:
        // cap nhat lai khi di lui 
        if(curStatelocation>0){
            curStatelocation-=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            btnBox1.setText(saveState.get(curStatelocation).board[0][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][0]));
            btnBox2.setText(saveState.get(curStatelocation).board[0][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][1]));
            btnBox3.setText(saveState.get(curStatelocation).board[0][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][2]));
            btnBox4.setText(saveState.get(curStatelocation).board[1][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][0]));
            btnBox5.setText(saveState.get(curStatelocation).board[1][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][1]));
            btnBox6.setText(saveState.get(curStatelocation).board[1][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][2]));
            btnBox7.setText(saveState.get(curStatelocation).board[2][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][0]));
            btnBox8.setText(saveState.get(curStatelocation).board[2][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][1]));
            btnBox9.setText(saveState.get(curStatelocation).board[2][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][2]));
            
        }
    }//GEN-LAST:event_jButtonDiLuiActionPerformed

    private void jButtonDiToiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiToiActionPerformed
        // TODO add your handling code here:
        // cap nhat lai khi di toi
        if(curStatelocation+1<saveState.size()){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            btnBox1.setText(saveState.get(curStatelocation).board[0][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][0]));
            btnBox2.setText(saveState.get(curStatelocation).board[0][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][1]));
            btnBox3.setText(saveState.get(curStatelocation).board[0][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][2]));
            btnBox4.setText(saveState.get(curStatelocation).board[1][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][0]));
            btnBox5.setText(saveState.get(curStatelocation).board[1][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][1]));
            btnBox6.setText(saveState.get(curStatelocation).board[1][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][2]));
            btnBox7.setText(saveState.get(curStatelocation).board[2][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][0]));
            btnBox8.setText(saveState.get(curStatelocation).board[2][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][1]));
            btnBox9.setText(saveState.get(curStatelocation).board[2][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][2]));
        }
    }//GEN-LAST:event_jButtonDiToiActionPerformed

    private void jButtonPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayAgainActionPerformed
        randomNumber();
    }//GEN-LAST:event_jButtonPlayAgainActionPerformed

    private void jButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolveActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        model puzzle = new model();
        // them trang thai hien tai vao puzzle.board de su dung thuat toan IDA* tim duong di
        puzzle.board[0][0] = (btnBox1.getText().equals("")) ? 0 : Integer.parseInt(btnBox1.getText());
        puzzle.board[0][1] = (btnBox2.getText().equals("")) ? 0 : Integer.parseInt(btnBox2.getText());
        puzzle.board[0][2] = (btnBox3.getText().equals("")) ? 0 : Integer.parseInt(btnBox3.getText());
        puzzle.board[1][0] = (btnBox4.getText().equals("")) ? 0 : Integer.parseInt(btnBox4.getText());
        puzzle.board[1][1] = (btnBox5.getText().equals("")) ? 0 : Integer.parseInt(btnBox5.getText());
        puzzle.board[1][2] = (btnBox6.getText().equals("")) ? 0 : Integer.parseInt(btnBox6.getText());
        puzzle.board[2][0] = (btnBox7.getText().equals("")) ? 0 : Integer.parseInt(btnBox7.getText());
        puzzle.board[2][1] = (btnBox8.getText().equals("")) ? 0 : Integer.parseInt(btnBox8.getText());
        puzzle.board[2][2] = (btnBox9.getText().equals("")) ? 0 : Integer.parseInt(btnBox9.getText());
        
            
        // gan vi tri o trong hien tai vao blankPos cua puzzle
        for(int i=0;i<SIZE;i++){
            for(int j=0;j<SIZE;j++){
                if(puzzle.board[i][j]==0){
                    puzzle.blankPos[0]=i;
                    puzzle.blankPos[1]=j;
                    break;
                }
            }
        }
        
        // khoi tao thoi gian bat dau chay tu vi tri nay
        long t1 = System.nanoTime();
        IDAStar idaStar = new IDAStar();
        ArrayList<model> path = idaStar.idaStar(puzzle);
        if(path.size()>0) path.remove(path.get(0));
        // kiem tra duong di tu dau den dich
//        for(model tmp: path){
//            for(int i=0;i<SIZE;i++){
//                for(int j=0;j<SIZE;j++){
//                    System.out.print(tmp.board[i][j] + " ");
//                }
//                System.out.println("");
//            }
//            System.out.println("");
//        }
        
        // them duong di tu vi tri hien tai den dich vao list trang thai
        saveState.addAll(path);
        
        // thoi gian chay thuat toan IDA* tim duong di
        double tDelta = (System.nanoTime() - t1) / 1e9;
        DecimalFormat decimalFormat = new DecimalFormat("#.##");
        
        // cap nhat thoi gian chay va so buoc di ra man hinh
        runningTime.setText( "Thời gian chạy: " + String.valueOf(decimalFormat.format(tDelta)) + "s");
        totalSteps.setText( "Tổng số bước đến đích: " + String.valueOf(path.size()));
        runningTime.setVisible(true);
        totalSteps.setVisible(true);
    }//GEN-LAST:event_jButtonSolveActionPerformed

    private void btnDich3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDich3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDich3ActionPerformed

    private void btnDich1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDich1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDich1ActionPerformed

    private void btnDich2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDich2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDich2ActionPerformed

    private void btnDich8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDich8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDich8ActionPerformed

    private void btnDich7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDich7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDich7ActionPerformed

    private void btnDich9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDich9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDich9ActionPerformed

    private void btnDich4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDich4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDich4ActionPerformed

    private void btnDich5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDich5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDich5ActionPerformed

    private void btnDich6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDich6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDich6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBox1;
    private javax.swing.JButton btnBox2;
    private javax.swing.JButton btnBox3;
    private javax.swing.JButton btnBox4;
    private javax.swing.JButton btnBox5;
    private javax.swing.JButton btnBox6;
    private javax.swing.JButton btnBox7;
    private javax.swing.JButton btnBox8;
    private javax.swing.JButton btnBox9;
    private javax.swing.JButton btnDich1;
    private javax.swing.JButton btnDich2;
    private javax.swing.JButton btnDich3;
    private javax.swing.JButton btnDich4;
    private javax.swing.JButton btnDich5;
    private javax.swing.JButton btnDich6;
    private javax.swing.JButton btnDich7;
    private javax.swing.JButton btnDich8;
    private javax.swing.JButton btnDich9;
    private javax.swing.JButton jButtonDiLui;
    private javax.swing.JButton jButtonDiToi;
    private javax.swing.JButton jButtonOut;
    private javax.swing.JButton jButtonPlayAgain;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JLabel jLabelTieuDe;
    private javax.swing.JLabel jLabelTongSoDiChuyen;
    private javax.swing.JPanel jPanelKhungHinhAnh;
    private javax.swing.JPanel jPanelKhungHinhAnh1;
    private javax.swing.JPanel jPanelTieuDe;
    private javax.swing.JLabel labelSoBuocDiChuyen;
    private javax.swing.JLabel runningTime;
    private javax.swing.JLabel totalSteps;
    // End of variables declaration//GEN-END:variables
}
