/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;
import java.awt.Image;
import java.awt.List;
import java.awt.Toolkit;
import java.io.File;
import java.math.RoundingMode;
import java.net.URI;
import java.net.URL;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.Locale;
import java.util.Random;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
/**
 *
 * @author Nghia
 */

/// nhung cho comment code duoc su dung de test khong xoa
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame 
     */
    int SIZE = 3;
    
    // luu cac trang thai da di qua
    ArrayList<model> saveState;
    
    // vi tri trang thai hien tai
    int curStatelocation = 0;
    
    public Frame() {
        initComponents();
        randomNumber();
        // khong hien len man hinh 
        runningTime.setVisible(false);
        totalSteps.setVisible(false);
    }
    
    // su dung de doi cho khi di chuyen
    int EmptyLocationChecker(JButton btn1 , JButton btn2){
         String BtnNumber = btn2.getText();
         if(BtnNumber.isEmpty()){
             btn2.setText(btn1.getText());
             btn1.setText("");
             return 1;
         }
         return 0;
    }
    
    // su dung de tinh so cap dao nguoc 
    // neu la chan thi co the giai duoc , le thi khong
    int countReversedPair(int[] a){
        int cnt = 0;
        for(int i=0;i<a.length-1;i++){
            for(int j=i+1;j<SIZE*SIZE;j++){
                if(a[i]!=0&&a[j]!=0&&a[i]>a[j]){
                    cnt++;
                }
            }
        }
        return cnt;
    }
    
    void randomNumber(){
        saveState = new ArrayList<>();
        jLabelTongSoDiChuyen.setText("0");
        curStatelocation = 0;
        int boardSize = SIZE;
        model puzzle = new model();
//        String [] num = {"1","2","3","4","5","6","","7","8"};
//        int [] arr = { 2 ,1, 3, 4 ,5, 6 ,8, 7 ,0 };
        int [] arr = new int[9];
        ArrayList<String> num = new ArrayList<>();

        for(int i=0;i<=8;i++){
            num.add(String.valueOf(i));
        }
        
        // neu vao truong hop khong giai duoc thi duyet lai
        while(true){
            Collections.shuffle(num);
            for(int i=0;i<SIZE*SIZE;i++){
                arr[i] = Integer.parseInt(num.get(i));
            }
            int checkSolve = countReversedPair(arr);
            if(checkSolve%2==0) break;
        }
        
        for(int i=0;i<SIZE*SIZE;i++){
            if(num.get(i).equals("0")){
                num.set(i, "");
            }
        }
        for(int i=0;i<SIZE;i++){
            for(int j=0;j<SIZE;j++){
                puzzle.board[i][j] = num.get(i*SIZE+j).equals("")?0:Integer.parseInt(num.get(i*SIZE+j));
            }
        }
        saveState.add(puzzle);
        jButtonPiece1.setText(num.get(0));
        jButtonPiece2.setText(num.get(1));
        jButtonPiece3.setText(num.get(2));
        jButtonPiece4.setText(num.get(3));
        jButtonPiece5.setText(num.get(4));
        jButtonPiece6.setText(num.get(5));
        jButtonPiece7.setText(num.get(6));
        jButtonPiece8.setText(num.get(7));
        jButtonPiece9.setText(num.get(8));
        
        
//        jButtonPiece1.setText(num[0]);
//        jButtonPiece2.setText(num[1]);
//        jButtonPiece3.setText(num[2]);
//        jButtonPiece4.setText(num[3]);
//        jButtonPiece5.setText(num[4]);
//        jButtonPiece6.setText(num[5]);
//        jButtonPiece7.setText(num[6]);
//        jButtonPiece8.setText(num[7]);
//        jButtonPiece9.setText(num[8]);

    }    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTieuDe = new javax.swing.JPanel();
        jLabelTieuDe = new javax.swing.JLabel();
        jPanelKhungHinhAnh = new javax.swing.JPanel();
        jButtonPiece3 = new javax.swing.JButton();
        jButtonPiece1 = new javax.swing.JButton();
        jButtonPiece2 = new javax.swing.JButton();
        jButtonPiece8 = new javax.swing.JButton();
        jButtonPiece7 = new javax.swing.JButton();
        jButtonPiece9 = new javax.swing.JButton();
        jButtonPiece4 = new javax.swing.JButton();
        jButtonPiece5 = new javax.swing.JButton();
        jButtonPiece6 = new javax.swing.JButton();
        jPanelAnhGoc = new javax.swing.JPanel();
        labelSoBuocDiChuyen = new javax.swing.JLabel();
        jButtonDiLui = new javax.swing.JButton();
        jButtonDiToi = new javax.swing.JButton();
        jLabelTongSoDiChuyen = new javax.swing.JLabel();
        jButtonOut = new javax.swing.JButton();
        jButtonPlayAgain = new javax.swing.JButton();
        jButtonSolve = new javax.swing.JButton();
        runningTime = new javax.swing.JLabel();
        totalSteps = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTieuDe.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTieuDe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(95, 158, 160), 1, true));
        jPanelTieuDe.setForeground(new java.awt.Color(0, 51, 255));

        jLabelTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTieuDe.setText("                          Puzzle Game in Java");

        javax.swing.GroupLayout jPanelTieuDeLayout = new javax.swing.GroupLayout(jPanelTieuDe);
        jPanelTieuDe.setLayout(jPanelTieuDeLayout);
        jPanelTieuDeLayout.setHorizontalGroup(
            jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTieuDeLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabelTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanelTieuDeLayout.setVerticalGroup(
            jPanelTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelTieuDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1550, -1));

        jPanelKhungHinhAnh.setBackground(new java.awt.Color(255, 255, 255));
        jPanelKhungHinhAnh.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Khung"));
        jPanelKhungHinhAnh.setForeground(new java.awt.Color(0, 51, 255));

        jButtonPiece3.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPiece3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonPiece3.setText("3");
        jButtonPiece3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiece3ActionPerformed(evt);
            }
        });

        jButtonPiece1.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPiece1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonPiece1.setText("1");
        jButtonPiece1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiece1ActionPerformed(evt);
            }
        });

        jButtonPiece2.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPiece2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonPiece2.setText("2");
        jButtonPiece2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiece2ActionPerformed(evt);
            }
        });

        jButtonPiece8.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPiece8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonPiece8.setText("8");
        jButtonPiece8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiece8ActionPerformed(evt);
            }
        });

        jButtonPiece7.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPiece7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonPiece7.setText("7");
        jButtonPiece7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiece7ActionPerformed(evt);
            }
        });

        jButtonPiece9.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPiece9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonPiece9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiece9ActionPerformed(evt);
            }
        });

        jButtonPiece4.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPiece4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonPiece4.setText("4");
        jButtonPiece4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiece4ActionPerformed(evt);
            }
        });

        jButtonPiece5.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPiece5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonPiece5.setText("5");
        jButtonPiece5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiece5ActionPerformed(evt);
            }
        });

        jButtonPiece6.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPiece6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonPiece6.setText("6");
        jButtonPiece6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiece6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelKhungHinhAnhLayout = new javax.swing.GroupLayout(jPanelKhungHinhAnh);
        jPanelKhungHinhAnh.setLayout(jPanelKhungHinhAnhLayout);
        jPanelKhungHinhAnhLayout.setHorizontalGroup(
            jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhungHinhAnhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKhungHinhAnhLayout.createSequentialGroup()
                        .addComponent(jButtonPiece1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPiece2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPiece3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelKhungHinhAnhLayout.createSequentialGroup()
                        .addComponent(jButtonPiece4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPiece5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPiece6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelKhungHinhAnhLayout.createSequentialGroup()
                        .addComponent(jButtonPiece7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPiece8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPiece9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelKhungHinhAnhLayout.setVerticalGroup(
            jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKhungHinhAnhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPiece1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPiece2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPiece3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPiece4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPiece5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPiece6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelKhungHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPiece7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPiece8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPiece9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelKhungHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 640, 660));

        jPanelAnhGoc.setBackground(new java.awt.Color(204, 204, 255));
        jPanelAnhGoc.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Anh goc"));

        javax.swing.GroupLayout jPanelAnhGocLayout = new javax.swing.GroupLayout(jPanelAnhGoc);
        jPanelAnhGoc.setLayout(jPanelAnhGocLayout);
        jPanelAnhGocLayout.setHorizontalGroup(
            jPanelAnhGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanelAnhGocLayout.setVerticalGroup(
            jPanelAnhGocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelAnhGoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 150, 640, 650));

        labelSoBuocDiChuyen.setBackground(new java.awt.Color(255, 51, 51));
        labelSoBuocDiChuyen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelSoBuocDiChuyen.setForeground(new java.awt.Color(51, 51, 255));
        labelSoBuocDiChuyen.setText("Số bước di chuyển:");
        getContentPane().add(labelSoBuocDiChuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 830, 220, 70));

        jButtonDiLui.setBackground(new java.awt.Color(255, 204, 153));
        jButtonDiLui.setText("<<Đi lùi");
        jButtonDiLui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiLuiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDiLui, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 850, 130, 40));

        jButtonDiToi.setBackground(new java.awt.Color(255, 204, 153));
        jButtonDiToi.setText(" Đi tới>>");
        jButtonDiToi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiToiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDiToi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 850, 130, 40));

        jLabelTongSoDiChuyen.setBackground(new java.awt.Color(102, 51, 255));
        jLabelTongSoDiChuyen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTongSoDiChuyen.setForeground(new java.awt.Color(0, 51, 255));
        jLabelTongSoDiChuyen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTongSoDiChuyen.setText("0");
        jLabelTongSoDiChuyen.setToolTipText("");
        getContentPane().add(jLabelTongSoDiChuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 850, 100, -1));

        jButtonOut.setText("Out");
        getContentPane().add(jButtonOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 840, 140, 40));

        jButtonPlayAgain.setText("play again");
        jButtonPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayAgainActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 840, 140, 40));

        jButtonSolve.setText("Solve");
        jButtonSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSolve, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 840, 140, 40));

        runningTime.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        runningTime.setText("Giải trong: ");
        getContentPane().add(runningTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 370, 40));

        totalSteps.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalSteps.setText("Số bước đi đến đích");
        getContentPane().add(totalSteps, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 380, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPiece3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiece3ActionPerformed
        int check = 0 ;
        
        check+=EmptyLocationChecker(jButtonPiece3, jButtonPiece2);
        check+=EmptyLocationChecker(jButtonPiece3, jButtonPiece6);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = jButtonPiece1.getText().equals("")?0:Integer.parseInt(jButtonPiece1.getText());
            puzzle.board[0][1] = jButtonPiece2.getText().equals("")?0:Integer.parseInt(jButtonPiece2.getText());
            puzzle.board[0][2] = jButtonPiece3.getText().equals("")?0:Integer.parseInt(jButtonPiece3.getText());
            puzzle.board[1][0] = jButtonPiece4.getText().equals("")?0:Integer.parseInt(jButtonPiece4.getText());
            puzzle.board[1][1] = jButtonPiece5.getText().equals("")?0:Integer.parseInt(jButtonPiece5.getText());
            puzzle.board[1][2] = jButtonPiece6.getText().equals("")?0:Integer.parseInt(jButtonPiece6.getText());
            puzzle.board[2][0] = jButtonPiece7.getText().equals("")?0:Integer.parseInt(jButtonPiece7.getText());
            puzzle.board[2][1] = jButtonPiece8.getText().equals("")?0:Integer.parseInt(jButtonPiece8.getText());
            puzzle.board[2][2] = jButtonPiece9.getText().equals("")?0:Integer.parseInt(jButtonPiece9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_jButtonPiece3ActionPerformed

    private void jButtonPiece1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiece1ActionPerformed
        int check = 0;
        
        check+=EmptyLocationChecker(jButtonPiece1, jButtonPiece2);
        check+=EmptyLocationChecker(jButtonPiece1, jButtonPiece4);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = jButtonPiece1.getText().equals("")?0:Integer.parseInt(jButtonPiece1.getText());
            puzzle.board[0][1] = jButtonPiece2.getText().equals("")?0:Integer.parseInt(jButtonPiece2.getText());
            puzzle.board[0][2] = jButtonPiece3.getText().equals("")?0:Integer.parseInt(jButtonPiece3.getText());
            puzzle.board[1][0] = jButtonPiece4.getText().equals("")?0:Integer.parseInt(jButtonPiece4.getText());
            puzzle.board[1][1] = jButtonPiece5.getText().equals("")?0:Integer.parseInt(jButtonPiece5.getText());
            puzzle.board[1][2] = jButtonPiece6.getText().equals("")?0:Integer.parseInt(jButtonPiece6.getText());
            puzzle.board[2][0] = jButtonPiece7.getText().equals("")?0:Integer.parseInt(jButtonPiece7.getText());
            puzzle.board[2][1] = jButtonPiece8.getText().equals("")?0:Integer.parseInt(jButtonPiece8.getText());
            puzzle.board[2][2] = jButtonPiece9.getText().equals("")?0:Integer.parseInt(jButtonPiece9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_jButtonPiece1ActionPerformed

    private void jButtonPiece2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiece2ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        check+=EmptyLocationChecker(jButtonPiece2, jButtonPiece1);
        check+=EmptyLocationChecker(jButtonPiece2, jButtonPiece3);
        check+=EmptyLocationChecker(jButtonPiece2, jButtonPiece5);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = jButtonPiece1.getText().equals("")?0:Integer.parseInt(jButtonPiece1.getText());
            puzzle.board[0][1] = jButtonPiece2.getText().equals("")?0:Integer.parseInt(jButtonPiece2.getText());
            puzzle.board[0][2] = jButtonPiece3.getText().equals("")?0:Integer.parseInt(jButtonPiece3.getText());
            puzzle.board[1][0] = jButtonPiece4.getText().equals("")?0:Integer.parseInt(jButtonPiece4.getText());
            puzzle.board[1][1] = jButtonPiece5.getText().equals("")?0:Integer.parseInt(jButtonPiece5.getText());
            puzzle.board[1][2] = jButtonPiece6.getText().equals("")?0:Integer.parseInt(jButtonPiece6.getText());
            puzzle.board[2][0] = jButtonPiece7.getText().equals("")?0:Integer.parseInt(jButtonPiece7.getText());
            puzzle.board[2][1] = jButtonPiece8.getText().equals("")?0:Integer.parseInt(jButtonPiece8.getText());
            puzzle.board[2][2] = jButtonPiece9.getText().equals("")?0:Integer.parseInt(jButtonPiece9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_jButtonPiece2ActionPerformed

    private void jButtonPiece7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiece7ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        
        
        check+=EmptyLocationChecker(jButtonPiece7, jButtonPiece4);
        check+=EmptyLocationChecker(jButtonPiece7, jButtonPiece8);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = jButtonPiece1.getText().equals("")?0:Integer.parseInt(jButtonPiece1.getText());
            puzzle.board[0][1] = jButtonPiece2.getText().equals("")?0:Integer.parseInt(jButtonPiece2.getText());
            puzzle.board[0][2] = jButtonPiece3.getText().equals("")?0:Integer.parseInt(jButtonPiece3.getText());
            puzzle.board[1][0] = jButtonPiece4.getText().equals("")?0:Integer.parseInt(jButtonPiece4.getText());
            puzzle.board[1][1] = jButtonPiece5.getText().equals("")?0:Integer.parseInt(jButtonPiece5.getText());
            puzzle.board[1][2] = jButtonPiece6.getText().equals("")?0:Integer.parseInt(jButtonPiece6.getText());
            puzzle.board[2][0] = jButtonPiece7.getText().equals("")?0:Integer.parseInt(jButtonPiece7.getText());
            puzzle.board[2][1] = jButtonPiece8.getText().equals("")?0:Integer.parseInt(jButtonPiece8.getText());
            puzzle.board[2][2] = jButtonPiece9.getText().equals("")?0:Integer.parseInt(jButtonPiece9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_jButtonPiece7ActionPerformed

    private void jButtonPiece8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiece8ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        check+=EmptyLocationChecker(jButtonPiece8, jButtonPiece5);
        check+=EmptyLocationChecker(jButtonPiece8, jButtonPiece7);
        check+=EmptyLocationChecker(jButtonPiece8, jButtonPiece9);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = jButtonPiece1.getText().equals("")?0:Integer.parseInt(jButtonPiece1.getText());
            puzzle.board[0][1] = jButtonPiece2.getText().equals("")?0:Integer.parseInt(jButtonPiece2.getText());
            puzzle.board[0][2] = jButtonPiece3.getText().equals("")?0:Integer.parseInt(jButtonPiece3.getText());
            puzzle.board[1][0] = jButtonPiece4.getText().equals("")?0:Integer.parseInt(jButtonPiece4.getText());
            puzzle.board[1][1] = jButtonPiece5.getText().equals("")?0:Integer.parseInt(jButtonPiece5.getText());
            puzzle.board[1][2] = jButtonPiece6.getText().equals("")?0:Integer.parseInt(jButtonPiece6.getText());
            puzzle.board[2][0] = jButtonPiece7.getText().equals("")?0:Integer.parseInt(jButtonPiece7.getText());
            puzzle.board[2][1] = jButtonPiece8.getText().equals("")?0:Integer.parseInt(jButtonPiece8.getText());
            puzzle.board[2][2] = jButtonPiece9.getText().equals("")?0:Integer.parseInt(jButtonPiece9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_jButtonPiece8ActionPerformed

    private void jButtonPiece9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiece9ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        
        
        check+=EmptyLocationChecker(jButtonPiece9, jButtonPiece6);
        check+=EmptyLocationChecker(jButtonPiece9, jButtonPiece8);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = jButtonPiece1.getText().equals("")?0:Integer.parseInt(jButtonPiece1.getText());
            puzzle.board[0][1] = jButtonPiece2.getText().equals("")?0:Integer.parseInt(jButtonPiece2.getText());
            puzzle.board[0][2] = jButtonPiece3.getText().equals("")?0:Integer.parseInt(jButtonPiece3.getText());
            puzzle.board[1][0] = jButtonPiece4.getText().equals("")?0:Integer.parseInt(jButtonPiece4.getText());
            puzzle.board[1][1] = jButtonPiece5.getText().equals("")?0:Integer.parseInt(jButtonPiece5.getText());
            puzzle.board[1][2] = jButtonPiece6.getText().equals("")?0:Integer.parseInt(jButtonPiece6.getText());
            puzzle.board[2][0] = jButtonPiece7.getText().equals("")?0:Integer.parseInt(jButtonPiece7.getText());
            puzzle.board[2][1] = jButtonPiece8.getText().equals("")?0:Integer.parseInt(jButtonPiece8.getText());
            puzzle.board[2][2] = jButtonPiece9.getText().equals("")?0:Integer.parseInt(jButtonPiece9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_jButtonPiece9ActionPerformed

    private void jButtonPiece4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiece4ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        check+=EmptyLocationChecker(jButtonPiece4, jButtonPiece1);
        check+=EmptyLocationChecker(jButtonPiece4, jButtonPiece5);
        check+=EmptyLocationChecker(jButtonPiece4, jButtonPiece7);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = jButtonPiece1.getText().equals("")?0:Integer.parseInt(jButtonPiece1.getText());
            puzzle.board[0][1] = jButtonPiece2.getText().equals("")?0:Integer.parseInt(jButtonPiece2.getText());
            puzzle.board[0][2] = jButtonPiece3.getText().equals("")?0:Integer.parseInt(jButtonPiece3.getText());
            puzzle.board[1][0] = jButtonPiece4.getText().equals("")?0:Integer.parseInt(jButtonPiece4.getText());
            puzzle.board[1][1] = jButtonPiece5.getText().equals("")?0:Integer.parseInt(jButtonPiece5.getText());
            puzzle.board[1][2] = jButtonPiece6.getText().equals("")?0:Integer.parseInt(jButtonPiece6.getText());
            puzzle.board[2][0] = jButtonPiece7.getText().equals("")?0:Integer.parseInt(jButtonPiece7.getText());
            puzzle.board[2][1] = jButtonPiece8.getText().equals("")?0:Integer.parseInt(jButtonPiece8.getText());
            puzzle.board[2][2] = jButtonPiece9.getText().equals("")?0:Integer.parseInt(jButtonPiece9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_jButtonPiece4ActionPerformed

    private void jButtonPiece5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiece5ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        check+=EmptyLocationChecker(jButtonPiece5, jButtonPiece2);
        check+=EmptyLocationChecker(jButtonPiece5, jButtonPiece4);
        check+=EmptyLocationChecker(jButtonPiece5, jButtonPiece6);
        check+=EmptyLocationChecker(jButtonPiece5, jButtonPiece8);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = jButtonPiece1.getText().equals("")?0:Integer.parseInt(jButtonPiece1.getText());
            puzzle.board[0][1] = jButtonPiece2.getText().equals("")?0:Integer.parseInt(jButtonPiece2.getText());
            puzzle.board[0][2] = jButtonPiece3.getText().equals("")?0:Integer.parseInt(jButtonPiece3.getText());
            puzzle.board[1][0] = jButtonPiece4.getText().equals("")?0:Integer.parseInt(jButtonPiece4.getText());
            puzzle.board[1][1] = jButtonPiece5.getText().equals("")?0:Integer.parseInt(jButtonPiece5.getText());
            puzzle.board[1][2] = jButtonPiece6.getText().equals("")?0:Integer.parseInt(jButtonPiece6.getText());
            puzzle.board[2][0] = jButtonPiece7.getText().equals("")?0:Integer.parseInt(jButtonPiece7.getText());
            puzzle.board[2][1] = jButtonPiece8.getText().equals("")?0:Integer.parseInt(jButtonPiece8.getText());
            puzzle.board[2][2] = jButtonPiece9.getText().equals("")?0:Integer.parseInt(jButtonPiece9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
    }//GEN-LAST:event_jButtonPiece5ActionPerformed

    private void jButtonPiece6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiece6ActionPerformed
        // TODO add your handling code here:
        int check = 0;
        check+=EmptyLocationChecker(jButtonPiece6, jButtonPiece3);
        check+=EmptyLocationChecker(jButtonPiece6, jButtonPiece5);
        check+=EmptyLocationChecker(jButtonPiece6, jButtonPiece9);
        if(check>0){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            model puzzle = new model();
            puzzle.board[0][0] = jButtonPiece1.getText().equals("")?0:Integer.parseInt(jButtonPiece1.getText());
            puzzle.board[0][1] = jButtonPiece2.getText().equals("")?0:Integer.parseInt(jButtonPiece2.getText());
            puzzle.board[0][2] = jButtonPiece3.getText().equals("")?0:Integer.parseInt(jButtonPiece3.getText());
            puzzle.board[1][0] = jButtonPiece4.getText().equals("")?0:Integer.parseInt(jButtonPiece4.getText());
            puzzle.board[1][1] = jButtonPiece5.getText().equals("")?0:Integer.parseInt(jButtonPiece5.getText());
            puzzle.board[1][2] = jButtonPiece6.getText().equals("")?0:Integer.parseInt(jButtonPiece6.getText());
            puzzle.board[2][0] = jButtonPiece7.getText().equals("")?0:Integer.parseInt(jButtonPiece7.getText());
            puzzle.board[2][1] = jButtonPiece8.getText().equals("")?0:Integer.parseInt(jButtonPiece8.getText());
            puzzle.board[2][2] = jButtonPiece9.getText().equals("")?0:Integer.parseInt(jButtonPiece9.getText());
            saveState.add(puzzle);
            System.out.println(curStatelocation);
        }
        
    }//GEN-LAST:event_jButtonPiece6ActionPerformed

    private void jButtonDiLuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiLuiActionPerformed
        // TODO add your handling code here:
        // cap nhat lai khi di lui 
        if(curStatelocation>0){
            curStatelocation-=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            jButtonPiece1.setText(saveState.get(curStatelocation).board[0][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][0]));
            jButtonPiece2.setText(saveState.get(curStatelocation).board[0][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][1]));
            jButtonPiece3.setText(saveState.get(curStatelocation).board[0][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][2]));
            jButtonPiece4.setText(saveState.get(curStatelocation).board[1][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][0]));
            jButtonPiece5.setText(saveState.get(curStatelocation).board[1][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][1]));
            jButtonPiece6.setText(saveState.get(curStatelocation).board[1][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][2]));
            jButtonPiece7.setText(saveState.get(curStatelocation).board[2][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][0]));
            jButtonPiece8.setText(saveState.get(curStatelocation).board[2][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][1]));
            jButtonPiece9.setText(saveState.get(curStatelocation).board[2][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][2]));
            
        }
    }//GEN-LAST:event_jButtonDiLuiActionPerformed

    private void jButtonDiToiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiToiActionPerformed
        // TODO add your handling code here:
        // cap nhat lai khi di toi
        if(curStatelocation+1<saveState.size()){
            curStatelocation+=1;
            jLabelTongSoDiChuyen.setText(String.valueOf(curStatelocation));
            jButtonPiece1.setText(saveState.get(curStatelocation).board[0][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][0]));
            jButtonPiece2.setText(saveState.get(curStatelocation).board[0][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][1]));
            jButtonPiece3.setText(saveState.get(curStatelocation).board[0][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[0][2]));
            jButtonPiece4.setText(saveState.get(curStatelocation).board[1][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][0]));
            jButtonPiece5.setText(saveState.get(curStatelocation).board[1][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][1]));
            jButtonPiece6.setText(saveState.get(curStatelocation).board[1][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[1][2]));
            jButtonPiece7.setText(saveState.get(curStatelocation).board[2][0]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][0]));
            jButtonPiece8.setText(saveState.get(curStatelocation).board[2][1]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][1]));
            jButtonPiece9.setText(saveState.get(curStatelocation).board[2][2]==0?"":String.valueOf(saveState.get(curStatelocation).board[2][2]));
        }
    }//GEN-LAST:event_jButtonDiToiActionPerformed

    private void jButtonPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayAgainActionPerformed
        randomNumber();
    }//GEN-LAST:event_jButtonPlayAgainActionPerformed

    private void jButtonSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolveActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        model puzzle = new model();
        // them trang thai hien tai vao puzzle.board de su dung thuat toan IDA* tim duong di
        puzzle.board[0][0] = (jButtonPiece1.getText().equals("")) ? 0 : Integer.parseInt(jButtonPiece1.getText());
        puzzle.board[0][1] = (jButtonPiece2.getText().equals("")) ? 0 : Integer.parseInt(jButtonPiece2.getText());
        puzzle.board[0][2] = (jButtonPiece3.getText().equals("")) ? 0 : Integer.parseInt(jButtonPiece3.getText());
        puzzle.board[1][0] = (jButtonPiece4.getText().equals("")) ? 0 : Integer.parseInt(jButtonPiece4.getText());
        puzzle.board[1][1] = (jButtonPiece5.getText().equals("")) ? 0 : Integer.parseInt(jButtonPiece5.getText());
        puzzle.board[1][2] = (jButtonPiece6.getText().equals("")) ? 0 : Integer.parseInt(jButtonPiece6.getText());
        puzzle.board[2][0] = (jButtonPiece7.getText().equals("")) ? 0 : Integer.parseInt(jButtonPiece7.getText());
        puzzle.board[2][1] = (jButtonPiece8.getText().equals("")) ? 0 : Integer.parseInt(jButtonPiece8.getText());
        puzzle.board[2][2] = (jButtonPiece9.getText().equals("")) ? 0 : Integer.parseInt(jButtonPiece9.getText());
        
            
        // gan vi tri o trong hien tai vao blankPos cua puzzle
        for(int i=0;i<SIZE;i++){
            for(int j=0;j<SIZE;j++){
                if(puzzle.board[i][j]==0){
                    puzzle.blankPos[0]=i;
                    puzzle.blankPos[1]=j;
                    break;
                }
            }
        }
        
        // khoi tao thoi gian bat dau chay tu vi tri nay
        long t1 = System.nanoTime();
        IDAStar idaStar = new IDAStar();
        ArrayList<model> path = idaStar.idaStar(puzzle);
        if(path.size()>0) path.remove(path.get(0));
        // kiem tra duong di tu dau den dich
//        for(model tmp: path){
//            for(int i=0;i<SIZE;i++){
//                for(int j=0;j<SIZE;j++){
//                    System.out.print(tmp.board[i][j] + " ");
//                }
//                System.out.println("");
//            }
//            System.out.println("");
//        }
        
        // them duong di tu vi tri hien tai den dich vao list trang thai
        saveState.addAll(path);
        
        // thoi gian chay thuat toan IDA* tim duong di
        double tDelta = (System.nanoTime() - t1) / 1e9;
        DecimalFormat decimalFormat = new DecimalFormat("#.##");
        
        // cap nhat thoi gian chay va so buoc di ra man hinh
        runningTime.setText( "Thời gian chạy: " + String.valueOf(decimalFormat.format(tDelta)) + "s");
        totalSteps.setText( "Tổng số bước đến đích: " + String.valueOf(path.size()));
        runningTime.setVisible(true);
        totalSteps.setVisible(true);
    }//GEN-LAST:event_jButtonSolveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDiLui;
    private javax.swing.JButton jButtonDiToi;
    private javax.swing.JButton jButtonOut;
    private javax.swing.JButton jButtonPiece1;
    private javax.swing.JButton jButtonPiece2;
    private javax.swing.JButton jButtonPiece3;
    private javax.swing.JButton jButtonPiece4;
    private javax.swing.JButton jButtonPiece5;
    private javax.swing.JButton jButtonPiece6;
    private javax.swing.JButton jButtonPiece7;
    private javax.swing.JButton jButtonPiece8;
    private javax.swing.JButton jButtonPiece9;
    private javax.swing.JButton jButtonPlayAgain;
    private javax.swing.JButton jButtonSolve;
    private javax.swing.JLabel jLabelTieuDe;
    private javax.swing.JLabel jLabelTongSoDiChuyen;
    private javax.swing.JPanel jPanelAnhGoc;
    private javax.swing.JPanel jPanelKhungHinhAnh;
    private javax.swing.JPanel jPanelTieuDe;
    private javax.swing.JLabel labelSoBuocDiChuyen;
    private javax.swing.JLabel runningTime;
    private javax.swing.JLabel totalSteps;
    // End of variables declaration//GEN-END:variables
}
